/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as api_archive from "../api/archive";
import type * as api_create from "../api/create";
import type * as api_getById from "../api/getById";
import type * as api_getSearch from "../api/getSearch";
import type * as api_getSidebar from "../api/getSidebar";
import type * as api_getTrash from "../api/getTrash";
import type * as api_remove from "../api/remove";
import type * as api_removeIcon from "../api/removeIcon";
import type * as api_restore from "../api/restore";
import type * as api_update from "../api/update";
import type * as documents from "../documents";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "api/archive": typeof api_archive;
  "api/create": typeof api_create;
  "api/getById": typeof api_getById;
  "api/getSearch": typeof api_getSearch;
  "api/getSidebar": typeof api_getSidebar;
  "api/getTrash": typeof api_getTrash;
  "api/remove": typeof api_remove;
  "api/removeIcon": typeof api_removeIcon;
  "api/restore": typeof api_restore;
  "api/update": typeof api_update;
  documents: typeof documents;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
